# Generated by Django 2.2.5 on 2019-09-29 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
