# Generated by Django 2.2.6 on 2019-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0003_post_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='instructor_image',
            field=models.ImageField(default='default.jpg', upload_to='instructor_images/'),
        ),
    ]
