# Generated by Django 2.2.6 on 2019-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0004_auto_20191102_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(max_length=2),
        ),
    ]
